export { default as filterContactsByName } from './filterContactsByName';
// export { default as getAvatar } from 'utils/getAvatar';
// export { default as getContactInfo } from 'utils/getContactInfo';
export { default as getPhoneNumber } from './getPhoneNumber';
// export { default as getUserInfo } from 'utils/getUserInfo';
// export { default as isAuthPage } from 'utils/isAuthPage';
export { default as getIsContactsPage } from './getIsContactsPage';
export { default as makeBlur } from './makeBlur';
// export { default as setAuthPageBackgroundColor } from 'utils/setAuthPageBackgroundColor';
export { default as setButtonColor } from './setButtonColor';
export { default as setIconFill } from './setIconFill';
export { default as setInputBorderColor } from './setInputBorderColor';
export { default as setInputBorderRadius } from './setInputBorderRadius';
export { default as setInputFilter } from './setInputFilter';
export { default as setInputFontColor } from './setInputFontColor';
export { default as setInputFontSize } from './setInputFontSize';
export { default as setInputHeight } from './setInputHeight';
export { default as setInputMaxWidth } from './setInputMaxWidth';
export { default as setInputPadding } from './setInputPadding';
export { default as sortContactsByName } from './sortContactsByName';
export { default as toasts } from './toasts';
export { default as updateSortSearchParams } from './updateSortSearchParams';
// export { default as getAuthPages } from 'utils/getAuthPages';
export { default as setIconHoverEffect } from './setIconHoverEffect';
export { default as filterEmptyFields } from './filterEmptyFields';
export { default as getProfileFormData } from './getProfileFormData';
export { default as onChangeAvatar } from './onChangeAvatar';
export { default as getPageNumbers } from './getPageNumbers';
export { default as getPaginationBarSettings } from './getPaginationBarSettings';
export { default as setBtnDisplayProp } from './setBtnDisplayProp';
export { default as getVisibleContacts } from './getVisibleContacts';
export { default as getTelegramLink } from './getTelegramLink';
export { default as getIsContact } from './getIsContact';
